export const smartphoneProducts = [
  {
    id: 101,
    name: 'iPhone 15 Pro Max',
    brand: 'Apple',
    category: 'Smartphone',
    productType: 'Flagship',
    price: 149999,
    discount: 10,
    originalPrice: 166666,
    images: [
      'https://www.apple.com/newsroom/images/2023/09/apple-unveils-iphone-15-pro-and-iphone-15-pro-max/tile/Apple-iPhone-15-Pro-lineup-hero-230912.jpg.news_app_ed.jpg',
      'https://www.imagineonline.store/cdn/shop/files/iPhone_15_Pro_Max_Blue_Titanium_PDP_Image_Position-1__en-IN_grande.jpg?v=1759734013',
    ],
    rating: 4.8,
    reviews: 1245,
    colour: 'Titanium Black',
    storage: '256GB',
    ram: '8GB',
    display: '6.7" Super Retina XDR',
    processor: 'A17 Pro Chip',
    camera: '48MP + 12MP + 12MP',
    battery: '4422 mAh',
    os: 'iOS 17',
    stock: 25,
    description: 'The ultimate iPhone with titanium design, A17 Pro chip, and advanced camera system.',
    features: [
      "Titanium design",
      "A17 Pro chip",
      "ProMotion display",
      "USB-C with USB 3",
      "5G capable"
    ],
    sku: 'IPHONE-15-PRO-MAX-256'
  },
  {
    id: 102,
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    category: 'Smartphone',
    productType: 'Flagship',
    price: 129999,
    discount: 15,
    originalPrice: 152941,
    images: [
      'https://reboxed.co/cdn/shop/files/s24ultra_violet_800x.webp?v=1758539202',
      'https://rukminim2.flixcart.com/image/480/640/xif0q/mobile/y/s/g/-original-imahgfmy2zgqvjmy.jpeg?q=90',
    ],
    rating: 4.7,
    reviews: 892,
    colour: 'Phantom Black',
    storage: '512GB',
    ram: '12GB',
    display: '6.8" Dynamic AMOLED 2X',
    processor: 'Snapdragon 8 Gen 3',
    camera: '200MP + 50MP + 12MP + 10MP',
    battery: '5000 mAh',
    os: 'Android 14',
    stock: 30,
    description: 'Revolutionary AI phone with Galaxy AI, 200MP camera, and Snapdragon 8 Gen 3.',
    features: [
      "Galaxy AI features",
      "200MP camera",
      "S Pen included",
      "Titanium frame",
      "7 years of OS updates"
    ],
    sku: 'S24-ULTRA-512'
  },
  {
    id: 103,
    name: 'Google Pixel 8 Pro',
    brand: 'Google',
    category: 'Smartphone',
    productType: 'Flagship',
    price: 89999,
    discount: 12,
    originalPrice: 102272,
    images: [
      'https://m.media-amazon.com/images/I/71r0349s3cL.jpg',
      'https://m.media-amazon.com/images/I/61Kf6WbQWyL._AC_UF894,1000_QL80_.jpg',
    ],
    rating: 4.6,
    reviews: 567,
    colour: 'Obsidian',
    storage: '128GB',
    ram: '12GB',
    display: '6.7" LTPO OLED',
    processor: 'Google Tensor G3',
    camera: '50MP + 48MP + 48MP',
    battery: '5050 mAh',
    os: 'Android 14',
    stock: 42,
    description: 'Powered by Google AI with best-in-class computational photography.',
    features: [
      "Tensor G3 chip",
      "Magic Editor",
      "Face Unblur",
      "7 years of updates",
      "Temperature sensor"
    ],
    sku: 'PIXEL-8-PRO-128'
  },
  {
    id: 104,
    name: 'OnePlus 12',
    brand: 'OnePlus',
    category: 'Smartphone',
    productType: 'Flagship',
    price: 69999,
    discount: 18,
    originalPrice: 85366,
    images: [
      'https://image01-in.oneplus.net/media/202407/04/41900be750fcc2707894c7eb516d1ce8.png',
      'https://m.media-amazon.com/images/I/71YzJwmRFCL._AC_UF1000,1000_QL80_.jpg'
    ],
    rating: 4.5,
    reviews: 423,
    colour: 'Flowy Emerald',
    storage: '256GB',
    ram: '12GB',
    display: '6.82" LTPO AMOLED',
    processor: 'Snapdragon 8 Gen 3',
    camera: '50MP + 48MP + 64MP',
    battery: '5400 mAh',
    os: 'OxygenOS 14',
    stock: 38,
    description: 'Fast and Smooth experience with 100W charging and Hasselblad camera.',
    features: [
      "100W SUPERVOOC charging",
      "Hasselblad camera",
      "Aqua Touch display",
      "Alert Slider",
      "Dolby Atmos"
    ],
    sku: 'ONEPLUS-12-256'
  },
  {
    id: 105,
    name: 'Xiaomi 14 Pro',
    brand: 'Xiaomi',
    category: 'Smartphone',
    productType: 'Flagship',
    price: 79999,
    discount: 20,
    originalPrice: 99999,
    images: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2IzvNaNevI4WEBOuBZmkeDvrsUUA1lFo2_g&s',
      'https://images.hindustantimes.com/tech/htmobile4/P37720/images/Design/150935-v4-xiaomi-14-pro-mobile-phone-large-2.jpg'
    ],
    rating: 4.4,
    reviews: 312,
    colour: 'Black',
    storage: '256GB',
    ram: '12GB',
    display: '6.73" C8 AMOLED',
    processor: 'Snapdragon 8 Gen 3',
    camera: '50MP Leica Summilux',
    battery: '4880 mAh',
    os: 'HyperOS',
    stock: 45,
    description: 'Leica photography experience with HyperOS and 120W HyperCharge.',
    features: [
      "Leica photography system",
      "120W HyperCharge",
      "Dragon Crystal glass",
      "IP68 rating",
      "Stereo speakers"
    ],
    sku: 'XIAOMI-14-PRO-256'
  },
  {
    id: 106,
    name: 'Nothing Phone (2)',
    brand: 'Nothing',
    category: 'Smartphone',
    productType: 'Premium',
    price: 49999,
    discount: 10,
    originalPrice: 55555,
    images: [
      'https://www.notebookcheck.net/typo3temp/_processed_/a/c/csm_BA_ALAK_200.1001_58836f6c04.jpg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfVUq84EueVugSVss50cP6QUUFNSuNeeMczQyPIoixVd7zrGX0lKyK0rXRzQvxNs1IlBg&usqp=CAU'
    ],
    rating: 4.3,
    reviews: 678,
    colour: 'White',
    storage: '256GB',
    ram: '12GB',
    display: '6.7" LTPO OLED',
    processor: 'Snapdragon 8+ Gen 1',
    camera: '50MP + 50MP',
    battery: '4700 mAh',
    os: 'Nothing OS 2.0',
    stock: 60,
    description: 'Unique Glyph Interface with transparent design and clean software.',
    features: [
      "Glyph Interface",
      "Transparent design",
      "Nothing OS 2.0",
      "45W charging",
      "Haptic Touch"
    ],
    sku: 'NOTHING-PHONE-2-256'
  },
  {
    id: 107,
    name: 'Samsung Galaxy A54 5G',
    brand: 'Samsung',
    category: 'Smartphone',
    productType: 'Mid-range',
    price: 34999,
    originalPrice: 46665,
    images: [
      'https://m.media-amazon.com/images/I/71kfHC4ANJL.jpg',
      'https://rukminim2.flixcart.com/image/480/640/xif0q/mobile/j/i/2/-original-imagq6bguqm5qbhh.jpeg?q=90'
    ],
    rating: 4.2,
    reviews: 891,
    colour: 'Awesome Violet',
    storage: '128GB',
    ram: '8GB',
    display: '6.4" Super AMOLED',
    processor: 'Exynos 1380',
    camera: '50MP + 12MP + 5MP',
    battery: '5000 mAh',
    os: 'Android 13',
    stock: 85,
    description: 'Premium mid-range with 120Hz AMOLED display and great camera.',
    features: [
      "120Hz AMOLED",
      "IP67 water resistant",
      "4 years of updates",
      "25W charging",
      "Stereo speakers"
    ],
    sku: 'A54-5G-128'
  },
  {
    id: 108,
    name: 'Google Pixel 7a',
    brand: 'Google',
    category: 'Smartphone',
    productType: 'Mid-range',
    price: 37999,
    discount: 15,
    originalPrice: 44705,
    images: [
      'https://rukminim2.flixcart.com/image/704/844/xif0q/mobile/l/2/y/-original-imaggswcffkgcupp.jpeg?q=20&crop=false',
      'https://rukminim2.flixcart.com/image/704/844/xif0q/mobile/q/b/o/pixel-7a-ghl1x-google-original-imah3j74pte7amu9.jpeg?q=20&crop=false',
    ],
    rating: 4.4,
    reviews: 756,
    colour: 'Sea',
    storage: '128GB',
    ram: '8GB',
    display: '6.1" OLED',
    processor: 'Google Tensor G2',
    camera: '64MP + 13MP',
    battery: '4385 mAh',
    os: 'Android 13',
    stock: 70,
    description: 'Google AI in a compact design with flagship-level camera.',
    features: [
      "Tensor G2 chip",
      "Night Sight",
      "Magic Eraser",
      "IP67 rating",
      "Wireless charging"
    ],
    sku: 'PIXEL-7A-128'
  },
  {
    id: 109,
    name: 'OnePlus Nord CE 3 Lite',
    brand: 'OnePlus',
    category: 'Smartphone',
    productType: 'Budget',
    price: 19999,
    originalPrice: 28570,
    images: [
      'https://cdnmedia.placewellretail.com/pub/media/catalog/product/cache/d2f155c8ae3423b25125c336aa39579e/q/e/qehdb.webp',
      'https://www.gadgetrebirth.com/cdn/shop/files/OnePlus_Nord_CE_3_Lite_Main.webp?v=1740861571'
    ],
    rating: 4.1,
    reviews: 934,
    colour: 'Pastel Lime',
    storage: '128GB',
    ram: '8GB',
    display: '6.72" LCD',
    processor: 'Snapdragon 695',
    camera: '108MP + 2MP + 2MP',
    battery: '5000 mAh',
    os: 'OxygenOS 13',
    stock: 120,
    description: '108MP camera with 67W fast charging at an affordable price.',
    features: [
      "108MP main camera",
      "67W SUPERVOOC",
      "120Hz display",
      "3.5mm headphone jack",
      "Expandable storage"
    ],
    sku: 'NORD-CE3-LITE-128'
  },
  {
    id: 110,
    name: 'Realme Narzo 60 Pro',
    brand: 'Realme',
    category: 'Smartphone',
    productType: 'Budget',
    price: 22999,
    originalPrice: 29487,
    images: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMIFBcMX-j9hTnGuKn9Mc16-9n54SIGqY6-sHQhQ5ssJ2eTVNhI2Wz27yqNX-yzUR7vqQ&usqp=CAU',
      'https://m.media-amazon.com/images/I/81ZV6G2iRrL.jpg'
    ],
    rating: 4.0,
    reviews: 657,
    colour: 'Mars Orange',
    storage: '128GB',
    ram: '8GB',
    display: '6.7" Curved AMOLED',
    processor: 'Dimensity 7050',
    camera: '100MP + 2MP',
    battery: '5000 mAh',
    os: 'Realme UI 4.0',
    stock: 95,
    description: 'Curved AMOLED display with 100MP camera and fast charging.',
    features: [
      "Curved AMOLED display",
      "100MP camera",
      "67W fast charging",
      "In-display fingerprint",
      "Dual speakers"
    ],
    sku: 'NARZO-60-PRO-128'
  },
  {
    id: 111,
    name: 'Vivo V29',
    brand: 'Vivo',
    category: 'Smartphone',
    productType: 'Mid-range',
    price: 32999,
    discount: 18,
    originalPrice: 40243,
    images: [
      'https://eshopy.in/wp-content/uploads/2023/12/v29-7.jpg',
      'https://cdn.beebom.com/mobile/2024/01/Vivo-V29-Pro-Black.png'
    ],
    rating: 4.2,
    reviews: 432,
    colour: 'Himalayan Blue',
    storage: '256GB',
    ram: '8GB',
    display: '6.78" AMOLED',
    processor: 'Snapdragon 778G',
    camera: '50MP with Aura Light',
    battery: '4600 mAh',
    os: 'Funtouch OS 13',
    stock: 65,
    description: 'Professional portrait photography with Aura Light feature.',
    features: [
      "Aura Light portrait",
      "120Hz AMOLED",
      "80W fast charging",
      "Ultra-slim design",
      "Smart color changing"
    ],
    sku: 'VIVO-V29-256'
  },
  {
    id: 112,
    name: 'iPhone 14',
    brand: 'Apple',
    category: 'Smartphone',
    productType: 'Premium',
    price: 69999,
    discount: 20,
    originalPrice: 87499,
    images: [
      'https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/310715_0_bjpqb7.png',
      'https://m.media-amazon.com/images/I/61cwywLZR-L._AC_UF1000,1000_QL80_.jpg',
    ],
    rating: 4.6,
    reviews: 1123,
    colour: 'Blue',
    storage: '128GB',
    ram: '6GB',
    display: '6.1" Super Retina XDR',
    processor: 'A15 Bionic',
    camera: '12MP + 12MP',
    battery: '3279 mAh',
    os: 'iOS 16',
    stock: 55,
    description: 'Advanced dual-camera system with Crash Detection and Emergency SOS.',
    features: [
      "A15 Bionic chip",
      "Ceramic Shield front",
      "Photonic Engine",
      "Action mode video",
      "Emergency SOS"
    ],
    sku: 'IPHONE-14-128'
  }
];